package org.mavai.punit.report.optimize;

import static org.mavai.punit.report.ReportHtml.escape;

import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.stream.LongStream;

import org.mavai.punit.internal.engine.emit.LatencySection;
import org.mavai.punit.report.ReportHtml;

/**
 * Renders the OPTIMIZE-experiment comparison report: a single,
 * self-contained HTML page summarising each optimize run — its iterations
 * ranked by the scorer, the chosen winner, a per-criterion matrix, and the
 * score trajectory across the run.
 *
 * <p>Reuses the test report's base stylesheet
 * ({@link ReportHtml#appendBaseCss}) for visual parity with the test
 * report and the exploration report, then appends a chart stylesheet for
 * the dependency-free bars and inline-SVG strips. No JavaScript, no
 * external asset, no chart library — the file renders fully offline.
 *
 * <p>Ranking is objective-aware (a higher score wins under
 * {@code MAXIMIZE}, a lower score under {@code MINIMIZE}) and is a plain
 * ordered sort, not a statistical claim.
 */
final class HtmlWriter {

    private static final DateTimeFormatter TIMESTAMP_FORMAT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss z")
                    .withZone(ZoneId.systemDefault());

    /** Percentile / token "not available" sentinel, rendered as a dash. */
    private static final long UNAVAILABLE = LatencySection.PERCENTILE_UNAVAILABLE_MS;

    /**
     * Relative score margin below which two adjacent ranked iterations are
     * "too close to call" on the objective. Presentational — a margin on
     * the ordering, not a significance test.
     */
    private static final double NEAR_TIE_SCORE_RELATIVE = 0.05;

    private HtmlWriter() {
    }

    static String generate(List<OptimizationRun> runs) {
        Instant now = Instant.now();
        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
        html.append("<meta charset=\"UTF-8\">\n");
        html.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        html.append("<title>PUnit Optimization Comparison</title>\n");
        ReportHtml.appendBaseCss(html);
        appendChartCss(html);
        html.append("</head>\n<body>\n");

        html.append("<header>\n");
        html.append("<h1>PUnit Optimization Comparison</h1>\n");
        html.append("<p class=\"timestamp\">Generated: ")
                .append(escape(TIMESTAMP_FORMAT.format(now))).append("</p>\n");
        html.append("</header>\n");

        html.append("<main>\n");
        if (runs.isEmpty()) {
            html.append("<p class=\"empty\">No optimizations found. Run an OPTIMIZE experiment "
                    + "to produce iteration data, then regenerate this report.</p>\n");
        } else {
            appendOverview(html, runs);
            if (runs.stream().anyMatch(r -> hasNearTie(r, ranked(r)))) {
                appendNearTieLegend(html);
            }
            for (OptimizationRun run : runs) {
                appendRun(html, run);
            }
        }
        html.append("</main>\n");

        html.append("<footer>\n");
        html.append("<p>Generated by PUnit at ")
                .append(escape(TIMESTAMP_FORMAT.format(now))).append("</p>\n");
        html.append("</footer>\n");
        html.append("</body>\n</html>\n");
        return html.toString();
    }

    // ── Overview ──────────────────────────────────────────────────────────

    private static void appendOverview(StringBuilder html, List<OptimizationRun> runs) {
        html.append("<section class=\"overview\">\n<h2>Overview</h2>\n");
        html.append("<table>\n<thead>\n<tr>");
        html.append("<th>Service</th><th>Experiment</th><th>Objective</th>");
        html.append("<th>Iterations</th><th>Best</th>");
        html.append("</tr>\n</thead>\n<tbody>\n");
        for (OptimizationRun run : runs) {
            html.append("<tr>\n");
            html.append("<td>").append(escape(run.service())).append("</td>\n");
            html.append("<td>").append(escape(run.experimentId())).append("</td>\n");
            html.append("<td>").append(escape(run.objective())).append("</td>\n");
            html.append("<td>").append(run.iterations().size()).append("</td>\n");
            html.append("<td>").append(bestCell(run)).append("</td>\n");
            html.append("</tr>\n");
        }
        html.append("</tbody>\n</table>\n</section>\n");
    }

    /**
     * The best cell: the top-ranked iteration, or — when the leading
     * iterations are too close to call — the whole leading cluster joined
     * by the near-tie marker.
     */
    private static String bestCell(OptimizationRun run) {
        List<Iteration> ranked = ranked(run);
        if (ranked.isEmpty()) {
            return "&mdash;";
        }
        StringBuilder cell = new StringBuilder(iterationRef(ranked.get(0)));
        for (int i = 1; i < ranked.size() && nearTie(run, ranked.get(i), ranked.get(i - 1)); i++) {
            cell.append(" <span class=\"tie-mark\">&asymp;</span> ").append(iterationRef(ranked.get(i)));
        }
        return cell.toString();
    }

    private static String iterationRef(Iteration it) {
        return "iteration " + it.index() + " (" + formatScore(it.score()) + ")";
    }

    private static void appendNearTieLegend(StringBuilder html) {
        html.append("<p class=\"tie-legend\"><span class=\"tie-mark\">&asymp;</span> ");
        html.append("Iterations sharing a rank are <strong>too close to call</strong>: their "
                + "scores are within 5% of each other on the objective. This flags a narrow "
                + "ordering margin for the reader's eye &mdash; it is not a significance test, and "
                + "the report makes no claim that one iteration is statistically better than "
                + "another. Tied iterations are ordered among themselves by latency, then cost.");
        html.append("</p>\n");
    }

    // ── Per-run section ─────────────────────────────────────────────────────

    private static void appendRun(StringBuilder html, OptimizationRun run) {
        List<Iteration> ranked = ranked(run);
        html.append("<section class=\"service\">\n");
        html.append("<h2>").append(escape(run.service())).append(" &middot; ")
                .append(escape(run.experimentId())).append("</h2>\n");
        appendConvergence(html, run);
        appendLeaderboard(html, run, ranked);
        appendCriterionMatrix(html, ranked);
        appendScoreTrajectory(html, run);
        html.append("</section>\n");
    }

    private static void appendConvergence(StringBuilder html, OptimizationRun run) {
        Convergence c = run.convergence();
        html.append("<p class=\"convergence\">");
        html.append("Objective <strong>").append(escape(run.objective())).append("</strong>");
        html.append(" &middot; ").append(run.iterations().size()).append(" iterations");
        if (c.bestIteration() >= 0) {
            html.append(" &middot; best: <strong>iteration ").append(c.bestIteration())
                    .append("</strong> (score ").append(formatScore(c.bestScore())).append(")");
        }
        if (c.terminationReason() != null) {
            html.append(" &middot; stopped: ").append(escape(c.terminationReason()));
        }
        html.append("</p>\n");
    }

    // ── (a) Iteration leaderboard ─────────────────────────────────────────────

    private static void appendLeaderboard(StringBuilder html, OptimizationRun run, List<Iteration> ranked) {
        long maxLatency = Math.max(1, ranked.stream()
                .flatMapToLong(it -> LongStream.of(it.p50Ms(), it.p95Ms()))
                .filter(ms -> ms != UNAVAILABLE).max().orElse(1));
        long maxAvg = Math.max(1, ranked.stream()
                .mapToLong(Iteration::avgTimePerSampleMs).max().orElse(1));
        double scoreMin = ranked.stream().mapToDouble(Iteration::score).min().orElse(0.0);
        double scoreMax = ranked.stream().mapToDouble(Iteration::score).max().orElse(0.0);
        int best = run.convergence().bestIteration();

        html.append("<h3>Iteration leaderboard</h3>\n");
        html.append("<table class=\"leaderboard\">\n<thead>\n<tr>");
        html.append("<th>#</th><th>Iteration</th><th>Score</th><th>Pass rate</th>");
        html.append("<th>p50</th><th>p95</th><th>Avg cost</th>");
        html.append("<th>Samples</th><th>Termination</th>");
        html.append("</tr>\n</thead>\n<tbody>\n");

        int[] ranks = competitionRanks(run, ranked);
        for (int i = 0; i < ranked.size(); i++) {
            Iteration it = ranked.get(i);
            html.append("<tr>\n");
            appendRankCell(html, run, ranked, ranks, i);
            appendIterationCell(html, it, it.index() == best);
            appendScoreCell(html, it, scoreMin, scoreMax, run.maximize());
            appendPassRateCell(html, it);
            appendLatencyCell(html, it.p50Ms(), maxLatency);
            appendLatencyCell(html, it.p95Ms(), maxLatency);
            appendCostCell(html, it, maxAvg);
            html.append("<td class=\"num\">").append(it.sampleCount()).append("</td>\n");
            appendTerminationCell(html, it.terminationReason());
            html.append("</tr>\n");
        }
        html.append("</tbody>\n</table>\n");
    }

    private static void appendIterationCell(StringBuilder html, Iteration it, boolean best) {
        html.append("<td>\n<details>\n<summary>iteration ").append(it.index());
        if (best) {
            html.append(" <span class=\"badge ok\">best</span>");
        }
        html.append("</summary>\n");
        html.append("<dl class=\"factor-list\">\n");
        for (Map.Entry<String, Object> factor : it.factors().entrySet()) {
            html.append("<dt>").append(escape(factor.getKey())).append("</dt>");
            html.append("<dd><pre>").append(escape(String.valueOf(factor.getValue())))
                    .append("</pre></dd>\n");
        }
        html.append("</dl>\n</details>\n</td>\n");
    }

    private static void appendScoreCell(StringBuilder html, Iteration it,
            double scoreMin, double scoreMax, boolean maximize) {
        double fraction = goodnessFraction(it.score(), scoreMin, scoreMax, maximize);
        html.append("<td class=\"score\">");
        html.append("<div class=\"bar-track\"><div class=\"bar-fill pass\" style=\"width:")
                .append(percent(fraction)).append("\"></div></div>");
        html.append("<span>").append(formatScore(it.score())).append("</span>");
        html.append("</td>\n");
    }

    private static void appendPassRateCell(StringBuilder html, Iteration it) {
        html.append("<td class=\"passrate\">\n");
        if (it.hasNoSamples()) {
            html.append("<div class=\"bar-track\"></div>\n");
            html.append("<span class=\"punit-inconclusive\">0/0</span>\n");
        } else {
            html.append("<div class=\"bar-track\">");
            html.append("<div class=\"bar-fill fail\" style=\"width:100%\"></div>");
            html.append("<div class=\"bar-fill pass\" style=\"width:")
                    .append(percent(it.observedRate())).append("\"></div>");
            html.append("</div>\n");
            html.append("<span>").append(it.successes()).append("/").append(it.sampleCount())
                    .append(" (").append(formatRate(it.observedRate())).append(")</span>\n");
        }
        html.append("</td>\n");
    }

    private static void appendLatencyCell(StringBuilder html, long valueMs, long maxLatency) {
        html.append("<td class=\"latency\">");
        if (valueMs == UNAVAILABLE) {
            html.append("<span class=\"muted\">-</span>");
        } else {
            html.append("<div class=\"bar-track narrow\"><div class=\"bar-fill muted\" style=\"width:")
                    .append(percent((double) valueMs / maxLatency)).append("\"></div></div>");
            html.append("<span>").append(valueMs).append("ms</span>");
        }
        html.append("</td>\n");
    }

    private static void appendCostCell(StringBuilder html, Iteration it, long maxAvg) {
        html.append("<td class=\"cost\">");
        html.append("<div class=\"bar-track narrow\"><div class=\"bar-fill muted\" style=\"width:")
                .append(percent((double) it.avgTimePerSampleMs() / maxAvg)).append("\"></div></div>");
        html.append("<span>").append(it.avgTimePerSampleMs()).append("ms");
        if (it.totalTokens() != UNAVAILABLE) {
            html.append(" &middot; ").append(it.totalTokens()).append(" tok");
        }
        html.append("</span></td>\n");
    }

    private static void appendTerminationCell(StringBuilder html, String reason) {
        String text = reason == null ? "&mdash;" : escape(reason);
        boolean completed = "COMPLETED".equals(reason);
        html.append("<td><span class=\"badge ").append(completed ? "ok" : "warn").append("\">")
                .append(text).append("</span></td>\n");
    }

    // ── (b) Per-criterion matrix ─────────────────────────────────────────────

    private static void appendCriterionMatrix(StringBuilder html, List<Iteration> ranked) {
        Set<String> criteria = new LinkedHashSet<>();
        ranked.forEach(it -> criteria.addAll(it.criteria().keySet()));
        if (criteria.isEmpty()) {
            return;
        }
        html.append("<h3>Per-criterion comparison</h3>\n");
        html.append("<table class=\"criterion-matrix\">\n<thead>\n<tr><th>Criterion</th>");
        for (Iteration it : ranked) {
            html.append("<th>iter ").append(it.index()).append("</th>");
        }
        html.append("</tr>\n</thead>\n<tbody>\n");
        for (String criterion : criteria) {
            html.append("<tr>\n<td class=\"criterion-name\">").append(escape(criterion)).append("</td>\n");
            for (Iteration it : ranked) {
                appendCriterionCell(html, it.criteria().get(criterion));
            }
            html.append("</tr>\n");
        }
        html.append("</tbody>\n</table>\n");
    }

    private static void appendCriterionCell(StringBuilder html, CriterionResult result) {
        if (result == null) {
            html.append("<td class=\"cell-na\"><span class=\"muted\">n/a</span></td>\n");
            return;
        }
        String rateClass = result.observedPassRate() >= 1.0 ? "punit-pass"
                : result.observedPassRate() <= 0.0 ? "punit-fail" : "";
        html.append("<td class=\"cell\">");
        html.append("<div class=\"bar-track narrow\"><div class=\"bar-fill pass\" style=\"width:")
                .append(percent(result.observedPassRate())).append("\"></div></div>");
        html.append("<span class=\"").append(rateClass).append("\">")
                .append(formatRate(result.observedPassRate())).append("</span>");
        html.append("</td>\n");
    }

    // ── (c) Score trajectory ──────────────────────────────────────────────────

    private static void appendScoreTrajectory(StringBuilder html, OptimizationRun run) {
        List<Iteration> byIndex = run.iterations().stream()
                .sorted(Comparator.comparingInt(Iteration::index)).toList();
        if (byIndex.isEmpty()) {
            return;
        }
        double min = byIndex.stream().mapToDouble(Iteration::score).min().orElse(0.0);
        double max = byIndex.stream().mapToDouble(Iteration::score).max().orElse(0.0);
        int best = run.convergence().bestIteration();
        int width = 360;
        int height = 60;
        int marginX = 8;
        int marginY = 10;
        int n = byIndex.size();

        html.append("<h3>Score trajectory</h3>\n");
        html.append("<svg class=\"trajectory-svg\" viewBox=\"0 0 ").append(width).append(" ").append(height)
                .append("\" width=\"").append(width).append("\" height=\"").append(height)
                .append("\" role=\"img\">");

        StringBuilder points = new StringBuilder();
        for (int i = 0; i < n; i++) {
            double x = trajectoryX(i, n, width, marginX);
            double y = trajectoryY(byIndex.get(i).score(), min, max, height, marginY);
            if (i > 0) {
                points.append(' ');
            }
            points.append(round(x)).append(',').append(round(y));
        }
        html.append("<polyline points=\"").append(points).append("\" class=\"trajectory-line\"/>");
        for (int i = 0; i < n; i++) {
            Iteration it = byIndex.get(i);
            double x = trajectoryX(i, n, width, marginX);
            double y = trajectoryY(it.score(), min, max, height, marginY);
            String cls = it.index() == best ? "trajectory-best" : "trajectory-dot";
            html.append("<circle cx=\"").append(round(x)).append("\" cy=\"").append(round(y))
                    .append("\" r=\"").append(it.index() == best ? "3.5" : "2.5")
                    .append("\" class=\"").append(cls).append("\"/>");
        }
        html.append("</svg>");
        html.append("<p class=\"trajectory-note\">Score per iteration (left&rarr;right = iteration order); "
                + "the marked point is the chosen best.</p>\n");
    }

    private static double trajectoryX(int i, int n, int width, int margin) {
        if (n <= 1) {
            return width / 2.0;
        }
        return margin + ((double) i / (n - 1)) * (width - 2 * margin);
    }

    private static double trajectoryY(double score, double min, double max, int height, int margin) {
        double frac = max == min ? 0.5 : (score - min) / (max - min);
        return height - margin - frac * (height - 2 * margin);
    }

    // ── Ranking + near-tie ──────────────────────────────────────────────────────

    private static List<Iteration> ranked(OptimizationRun run) {
        Comparator<Iteration> byScore = Comparator.comparingDouble(Iteration::score);
        if (run.maximize()) {
            byScore = byScore.reversed();
        }
        Comparator<Iteration> rank = byScore
                .thenComparingLong(HtmlWriter::p50ForRanking)
                .thenComparingLong(Iteration::avgTimePerSampleMs);
        return run.iterations().stream().sorted(rank).toList();
    }

    private static boolean hasNearTie(OptimizationRun run, List<Iteration> ranked) {
        for (int i = 1; i < ranked.size(); i++) {
            if (nearTie(run, ranked.get(i), ranked.get(i - 1))) {
                return true;
            }
        }
        return false;
    }

    /**
     * Two iterations are too close to call when their scores are within
     * {@link #NEAR_TIE_SCORE_RELATIVE} of each other. Presentational — the
     * report makes no inferential claim; tied iterations are simply ordered
     * by the secondary keys.
     */
    private static boolean nearTie(OptimizationRun run, Iteration a, Iteration b) {
        double larger = Math.max(Math.abs(a.score()), Math.abs(b.score()));
        if (larger == 0.0) {
            return true;
        }
        return Math.abs(a.score() - b.score()) / larger < NEAR_TIE_SCORE_RELATIVE;
    }

    private static int[] competitionRanks(OptimizationRun run, List<Iteration> ranked) {
        int[] ranks = new int[ranked.size()];
        for (int i = 0; i < ranked.size(); i++) {
            ranks[i] = (i > 0 && nearTie(run, ranked.get(i), ranked.get(i - 1))) ? ranks[i - 1] : i + 1;
        }
        return ranks;
    }

    private static void appendRankCell(StringBuilder html, OptimizationRun run,
            List<Iteration> ranked, int[] ranks, int i) {
        boolean tiedWithPrev = i > 0 && nearTie(run, ranked.get(i), ranked.get(i - 1));
        boolean tiedWithNext = i + 1 < ranked.size() && nearTie(run, ranked.get(i + 1), ranked.get(i));
        html.append("<td class=\"rank\">").append(ranks[i]);
        if (tiedWithPrev || tiedWithNext) {
            html.append("<span class=\"tie-mark\" title=\"Too close to call: score within 5% of the "
                    + "adjacent iteration — a presentational margin, not a significance test.\">&asymp;</span>");
        }
        html.append("</td>\n");
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private static long p50ForRanking(Iteration it) {
        return it.p50Ms() == UNAVAILABLE ? Long.MAX_VALUE : it.p50Ms();
    }

    private static double goodnessFraction(double score, double min, double max, boolean maximize) {
        if (max == min) {
            return 1.0;
        }
        double frac = maximize ? (score - min) / (max - min) : (max - score) / (max - min);
        return Math.max(0.0, Math.min(1.0, frac));
    }

    private static String percent(double fraction) {
        double clamped = Math.max(0.0, Math.min(1.0, fraction));
        return String.format(Locale.ROOT, "%.2f%%", clamped * 100.0);
    }

    private static String formatRate(double rate) {
        return String.format(Locale.ROOT, "%.1f%%", rate * 100.0);
    }

    private static String formatScore(double score) {
        return String.format(Locale.ROOT, "%.3f", score);
    }

    private static String round(double value) {
        return String.format(Locale.ROOT, "%.1f", value);
    }

    private static void appendChartCss(StringBuilder html) {
        html.append("<style>\n");
        html.append("""
                h3 { font-size: 1rem; margin: 1rem 0 0.5rem; color: var(--text-color); }
                .service { margin-bottom: 2.5rem; }
                .overview { margin-bottom: 2rem; }
                p.empty { color: var(--text-muted); font-style: italic; }
                p.convergence { font-size: 0.875rem; color: var(--text-color); margin-bottom: 0.5rem; }
                td.rank, td.num { text-align: right; font-variant-numeric: tabular-nums; }
                .tie-mark {
                    color: var(--text-muted);
                    font-weight: 600;
                    margin-left: 0.15rem;
                    cursor: help;
                }
                p.tie-legend {
                    margin: -1rem 0 1.5rem;
                    padding: 0.5rem 0.75rem;
                    background: var(--bg-light);
                    border: 1px solid var(--border-color);
                    border-left: 3px solid var(--text-muted);
                    border-radius: 4px;
                    font-size: 0.8125rem;
                    color: var(--text-color);
                    line-height: 1.5;
                }
                table.leaderboard td { vertical-align: middle; }
                .bar-track {
                    position: relative;
                    display: inline-block;
                    width: 120px;
                    height: 0.9rem;
                    background: var(--bg-light);
                    border: 1px solid var(--border-color);
                    border-radius: 3px;
                    overflow: hidden;
                    vertical-align: middle;
                }
                .bar-track.narrow { width: 80px; }
                .bar-fill {
                    position: absolute;
                    left: 0;
                    top: 0;
                    bottom: 0;
                }
                .bar-fill.pass { background: var(--pass-color); }
                .bar-fill.fail { background: var(--fail-color); }
                .bar-fill.muted { background: #adb5bd; }
                td.score span, td.passrate span, td.latency span, td.cost span, td.cell span {
                    margin-left: 0.4rem;
                    font-variant-numeric: tabular-nums;
                    font-size: 0.8125rem;
                }
                .muted { color: var(--text-muted); }
                .badge {
                    display: inline-block;
                    padding: 0.1rem 0.5rem;
                    border-radius: 3px;
                    font-size: 0.75rem;
                    font-weight: 600;
                }
                .badge.ok { background: #e8f5e9; color: var(--pass-color); }
                .badge.warn { background: #fff8e1; color: #b26a00; border: 1px solid #f9a825; }
                dl.factor-list {
                    display: grid;
                    grid-template-columns: max-content 1fr;
                    column-gap: 1rem;
                    row-gap: 0.25rem;
                    margin: 0.5rem 0 0.25rem 0.5rem;
                    font-size: 0.8125rem;
                }
                dl.factor-list dt { color: var(--text-muted); font-family: monospace; }
                dl.factor-list dd { margin: 0; }
                dl.factor-list pre {
                    margin: 0;
                    white-space: pre-wrap;
                    word-wrap: break-word;
                    font-size: 0.8125rem;
                }
                table.criterion-matrix td.criterion-name { font-family: monospace; font-size: 0.8125rem; }
                table.criterion-matrix td.cell, table.criterion-matrix td.cell-na { white-space: nowrap; }
                svg.trajectory-svg {
                    border: 1px solid var(--border-color);
                    border-radius: 4px;
                    background: var(--bg-white);
                    vertical-align: middle;
                }
                .trajectory-line { fill: none; stroke: #adb5bd; stroke-width: 1.5; }
                .trajectory-dot { fill: #6c757d; }
                .trajectory-best { fill: var(--pass-color); }
                p.trajectory-note { font-size: 0.8125rem; color: var(--text-muted); margin-top: 0.25rem; }
                """);
        html.append("</style>\n");
    }
}
