package org.mavai.punit.internal.engine.spec.model;

import java.time.Instant;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.mavai.punit.api.covariate.CovariateDeclaration;
import org.mavai.punit.api.covariate.CovariateProfile;
import org.mavai.punit.verdict.ExpirationPolicy;
import org.mavai.punit.verdict.ExpirationStatus;
import org.mavai.punit.api.ServiceContractAttributes;

/**
 * An execution specification containing empirical data for probabilistic testing.
 *
 * <p>Specifications are the unified artifact that drives probabilistic tests. They contain:
 * <ul>
 *   <li><strong>Empirical basis</strong>: Raw observations (samples, successes) from experiments,
 *       used for threshold derivation at runtime</li>
 *   <li><strong>Configuration</strong>: Context for test execution (model, temperature, etc.)</li>
 *   <li><strong>Cost envelope</strong>: Resource limits (time, tokens)</li>
 *   <li><strong>Extended statistics</strong>: Optional detailed metrics (failure distribution, etc.)</li>
 * </ul>
 *
 * <h2>Simplified Workflow</h2>
 * <p>Specs are generated directly by experiments and committed to version control.
 * Approval happens through Git commit (with optional PR review). There is no separate
 * "baseline" artifact or approval command.
 *
 * <h2>Threshold Derivation</h2>
 * <p>The specification does <em>not</em> contain pre-computed thresholds. Instead,
 * thresholds are derived at test runtime based on the empirical basis and the
 * operational approach specified in the {@code @ProbabilisticTest} annotation.
 *
 * <h2>Schema Versions</h2>
 * <ul>
 *   <li>{@code punit-spec-1}: Original format with required approval metadata</li>
 *   <li>{@code punit-spec-2}: Simplified format with optional approval metadata</li>
 * </ul>
 */
public final class ExecutionSpecification {

	private final String serviceContractId;
	private final int version;
	private final Instant generatedAt;
	private final Instant approvedAt;
	private final String approvedBy;
	private final String approvalNotes;
	private final List<String> sourceBaselines;
	private final Map<String, Object> executionContext;
	private final SpecRequirements requirements;
	private final CostEnvelope costEnvelope;
	private final EmpiricalBasis empiricalBasis;
	private final ExtendedStatistics extendedStatistics;
	private final FactorSourceMetadata factorSourceMetadata;
	private final ExpirationPolicy expirationPolicy;
	private final CovariateProfile covariateProfile;
	private final String footprint;
	private final LatencyBaseline latencyBaseline;
	private final ServiceContractAttributes serviceContractAttributes;

	private ExecutionSpecification(Builder builder) {
		this.serviceContractId = Objects.requireNonNull(builder.serviceContractId, "serviceContractId must not be null");
		this.version = builder.version;
		this.generatedAt = builder.generatedAt;
		this.approvedAt = builder.approvedAt;
		this.approvedBy = builder.approvedBy;
		this.approvalNotes = builder.approvalNotes;
		this.sourceBaselines = builder.sourceBaselines != null
				? List.copyOf(builder.sourceBaselines)
				: Collections.emptyList();
		this.executionContext = builder.executionContext != null
				? Collections.unmodifiableMap(new LinkedHashMap<>(builder.executionContext))
				: Collections.emptyMap();
		this.requirements = builder.requirements != null
				? builder.requirements
				: new SpecRequirements(1.0, "");
		this.costEnvelope = builder.costEnvelope;
		this.empiricalBasis = builder.empiricalBasis;
		this.extendedStatistics = builder.extendedStatistics;
		this.factorSourceMetadata = builder.factorSourceMetadata;
		this.expirationPolicy = builder.expirationPolicy;
		this.covariateProfile = builder.covariateProfile;
		this.footprint = builder.footprint;
		this.latencyBaseline = builder.latencyBaseline;
		this.serviceContractAttributes = builder.serviceContractAttributes != null
				? builder.serviceContractAttributes : ServiceContractAttributes.DEFAULT;
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * Returns the service contract ID.
	 *
	 * <p>This is the primary identifier for both the service contract and the specification.
	 *
	 * @return the service contract ID
	 */
	public String getServiceContractId() {
		return serviceContractId;
	}

	public int getVersion() {
		return version;
	}

	/**
	 * Returns when this specification was generated by an experiment.
	 *
	 * @return the generation timestamp, or null if not recorded
	 */
	public Instant getGeneratedAt() {
		return generatedAt;
	}

	/**
	 * Returns when this specification was approved.
	 *
	 * <p>Note: In the simplified workflow (punit-spec-2), approval metadata is optional
	 * since approval happens through Git commit. This field may be null.
	 *
	 * @return the approval timestamp, or null if not recorded
	 */
	public Instant getApprovedAt() {
		return approvedAt;
	}

	/**
	 * Returns who approved this specification.
	 *
	 * <p>Note: In the simplified workflow (punit-spec-2), approval metadata is optional
	 * since approval happens through Git commit. This field may be null.
	 *
	 * @return the approver name, or null if not recorded
	 */
	public String getApprovedBy() {
		return approvedBy;
	}

	public String getApprovalNotes() {
		return approvalNotes;
	}

	public List<String> getSourceBaselines() {
		return sourceBaselines;
	}

	public Map<String, Object> getExecutionContext() {
		return executionContext;
	}

	public SpecRequirements getRequirements() {
		return requirements;
	}

	public CostEnvelope getCostEnvelope() {
		return costEnvelope;
	}

	/**
	 * Returns the empirical basis used for threshold derivation.
	 *
	 * <p>This data is essential for computing thresholds at runtime based on
	 * the operational approach specified in the test annotation.
	 *
	 * @return the empirical basis, or null if not set (older specs)
	 */
	public EmpiricalBasis getEmpiricalBasis() {
		return empiricalBasis;
	}

	/**
	 * Returns extended statistics from the experiment.
	 *
	 * <p>This optional data provides additional detail for analysis but is not
	 * required for threshold derivation.
	 *
	 * @return extended statistics, or null if not recorded
	 */
	public ExtendedStatistics getExtendedStatistics() {
		return extendedStatistics;
	}

	/**
	 * Returns the factor source metadata from the experiment.
	 *
	 * <p>This metadata enables factor consistency verification between experiments
	 * and probabilistic tests. If the test uses a factor source with the same hash,
	 * the first-N factors consumed will be identical.
	 *
	 * @return factor source metadata, or null if not recorded
	 */
	public FactorSourceMetadata getFactorSourceMetadata() {
		return factorSourceMetadata;
	}

	/**
	 * Returns true if this specification has factor source metadata.
	 *
	 * @return true if factor source metadata is present
	 */
	public boolean hasFactorSourceMetadata() {
		return factorSourceMetadata != null && factorSourceMetadata.hasHash();
	}

	/**
	 * Returns the expiration policy for this baseline.
	 *
	 * <p>The expiration policy defines how long the baseline remains valid
	 * after the experiment end time. Use {@link #evaluateExpiration(Instant)}
	 * to check the current status.
	 *
	 * @return the expiration policy, or null if no policy was set
	 */
	public ExpirationPolicy getExpirationPolicy() {
		return expirationPolicy;
	}

	/**
	 * Returns true if this specification has an expiration policy.
	 *
	 * @return true if an expiration policy is present and has a non-zero validity period
	 */
	public boolean hasExpirationPolicy() {
		return expirationPolicy != null && expirationPolicy.hasExpiration();
	}

	/**
	 * Returns the covariate profile captured during the experiment.
	 *
	 * <p>The covariate profile contains the environmental conditions under which
	 * the baseline was established, used for conformance checking during tests.
	 *
	 * <p>If the spec has a warmup value, it is injected as an implicit covariate
	 * in the returned profile (appearing first), ensuring baseline selection
	 * matches on warmup as a CONFIGURATION covariate.
	 *
	 * @return the covariate profile, or null if not recorded and no warmup
	 */
	public CovariateProfile getCovariateProfile() {
		boolean hasImplicit = serviceContractAttributes.hasWarmup() || serviceContractAttributes.hasMaxConcurrent();
		if (hasImplicit) {
			LinkedHashMap<String, String> merged = new LinkedHashMap<>();
			if (serviceContractAttributes.hasWarmup()) {
				merged.put(CovariateDeclaration.KEY_WARMUP, String.valueOf(serviceContractAttributes.warmup()));
			}
			if (serviceContractAttributes.hasMaxConcurrent()) {
				merged.put(CovariateDeclaration.KEY_MAX_CONCURRENT, String.valueOf(serviceContractAttributes.maxConcurrent()));
			}
			if (covariateProfile != null) {
				merged.putAll(covariateProfile.values());
			}
			return CovariateProfile.of(merged);
		}
		return covariateProfile;
	}

	/**
	 * Returns true if this specification has a covariate profile.
	 *
	 * @return true if a covariate profile is present
	 */
	public boolean hasCovariateProfile() {
		return covariateProfile != null && !covariateProfile.isEmpty();
	}

	/**
	 * Returns the invocation footprint.
	 *
	 * <p>The footprint uniquely identifies the combination of service contract,
	 * factors, and covariate declarations. Only baselines with matching
	 * footprints are candidates for selection.
	 *
	 * @return the footprint hash, or null if not recorded
	 */
	public String getFootprint() {
		return footprint;
	}

	/**
	 * Returns the service contract attributes from the spec.
	 *
	 * @return the service contract attributes (never null)
	 */
	public ServiceContractAttributes getServiceContractAttributes() {
		return serviceContractAttributes;
	}

	/**
	 * Returns the warmup count used when this baseline was measured.
	 *
	 * <p>0 means no warmup was used (or the spec predates the warmup feature).
	 *
	 * @return the warmup count (>= 0)
	 */
	public int getWarmup() {
		return serviceContractAttributes.warmup();
	}

	/**
	 * Returns true if this specification has a footprint.
	 *
	 * @return true if a footprint is present
	 */
	public boolean hasFootprint() {
		return footprint != null && !footprint.isEmpty();
	}

	/**
	 * Returns the latency baseline from the experiment.
	 *
	 * <p>This data captures the distributional latency profile of successful
	 * samples. It is used for baseline-derived latency threshold computation.
	 *
	 * @return the latency baseline, or null if not recorded
	 */
	public LatencyBaseline getLatencyBaseline() {
		return latencyBaseline;
	}

	/**
	 * Returns true if this specification has latency baseline data.
	 *
	 * @return true if latency baseline is present
	 */
	public boolean hasLatencyBaseline() {
		return latencyBaseline != null;
	}

	/**
	 * Evaluates the expiration status at the given time.
	 *
	 * <p>Convenience method that delegates to the expiration policy.
	 * Returns {@link ExpirationStatus.NoExpiration} if no policy is set.
	 *
	 * @param currentTime the time at which to evaluate
	 * @return the expiration status
	 */
	public ExpirationStatus evaluateExpiration(Instant currentTime) {
		if (expirationPolicy == null) {
			return ExpirationStatus.noExpiration();
		}
		return expirationPolicy.evaluateAt(currentTime);
	}

	/**
	 * Returns true if this specification has empirical basis for threshold derivation.
	 *
	 * @return true if empirical basis is present
	 */
	public boolean hasEmpiricalBasis() {
		return empiricalBasis != null && empiricalBasis.samples() > 0;
	}

	/**
	 * Returns the number of samples from the baseline experiment.
	 *
	 * @return the baseline sample count, or 0 if no empirical basis
	 */
	public int getBaselineSamples() {
		return empiricalBasis != null ? empiricalBasis.samples() : 0;
	}

	/**
	 * Returns the number of successes from the baseline experiment.
	 *
	 * @return the baseline success count, or 0 if no empirical basis
	 */
	public int getBaselineSuccesses() {
		return empiricalBasis != null ? empiricalBasis.successes() : 0;
	}

	/**
	 * Returns the observed success rate from the baseline experiment.
	 *
	 * @return the observed rate (0.0 to 1.0), or 0.0 if no empirical basis
	 */
	public double getObservedRate() {
		if (empiricalBasis == null || empiricalBasis.samples() == 0) {
			return 0.0;
		}
		return (double) empiricalBasis.successes() / empiricalBasis.samples();
	}

	/**
	 * Returns true if this specification has explicit approval metadata.
	 *
	 * <p>Note: In the simplified workflow (punit-spec-2), approval metadata is optional.
	 * A spec without explicit approval is still valid if it has empirical basis.
	 *
	 * @return true if approval metadata is present
	 */
	public boolean hasApprovalMetadata() {
		return approvedAt != null && approvedBy != null && !approvedBy.isEmpty();
	}

	/**
	 * Returns the minimum pass rate from requirements.
	 *
	 * @return the minimum pass rate
	 */
	public double getMinPassRate() {
		return requirements.minPassRate();
	}

	/**
	 * Returns the success criteria from requirements.
	 *
	 * @return the success criteria
	 */
	public SuccessCriteria getSuccessCriteria() {
		String criteria = requirements.successCriteria();
		if (criteria == null || criteria.isEmpty()) {
			return SuccessCriteria.alwaysTrue();
		}
		return SuccessCriteria.parse(criteria);
	}

	/**
	 * Validates this specification.
	 *
	 * <p>Validation rules:
	 * <ul>
	 *   <li>For schema v1: approval metadata is required</li>
	 *   <li>For schema v2: empirical basis is required, approval is optional</li>
	 *   <li>minPassRate must be in range [0.0, 1.0]</li>
	 * </ul>
	 *
	 * @throws SpecificationValidationException if validation fails
	 */
	public void validate() throws SpecificationValidationException {
		// Check minPassRate bounds
		if (requirements.minPassRate() < 0.0 || requirements.minPassRate() > 1.0) {
			throw new SpecificationValidationException(
					"Specification '" + serviceContractId + "' has invalid minPassRate: " + requirements.minPassRate());
		}

		// For backwards compatibility: if approval metadata is present, it's valid
		// For new specs: empirical basis is preferred but not strictly required
		// This allows both v1 (approval-based) and v2 (empirical-based) specs
		
		// Note: We don't require approval metadata anymore for v2 specs.
		// The presence of the spec in version control IS the approval.
	}

	/**
	 * Specification requirements.
	 */
	public record SpecRequirements(double minPassRate, String successCriteria) {
	}

	/**
	 * Cost envelope for resource limits.
	 */
	public record CostEnvelope(long maxTimePerSampleMs, long maxTokensPerSample, long totalTokenBudget) {
	}

	/**
	 * Empirical basis from the experiment, used for threshold derivation at runtime.
	 *
	 * <p>This record contains the essential observations needed to compute
	 * statistically-sound thresholds based on the operational approach.
	 *
	 * @param samples Total number of trials in the experiment
	 * @param successes Number of successful trials
	 * @param generatedAt When the experiment was run
	 */
	public record EmpiricalBasis(int samples, int successes, Instant generatedAt) {

		/**
		 * Returns the observed success rate.
		 *
		 * @return the rate (0.0 to 1.0)
		 */
		public double observedRate() {
			if (samples == 0) return 0.0;
			return (double) successes / samples;
		}

		/**
		 * Validates that the empirical basis is consistent.
		 *
		 * @throws IllegalArgumentException if data is invalid
		 */
		public EmpiricalBasis {
			if (samples < 0) {
				throw new IllegalArgumentException("samples must be non-negative");
			}
			if (successes < 0) {
				throw new IllegalArgumentException("successes must be non-negative");
			}
			if (successes > samples) {
				throw new IllegalArgumentException("successes cannot exceed samples");
			}
		}
	}

	/**
	 * Extended statistics from the experiment.
	 *
	 * <p>This data provides additional detail for analysis but is not required
	 * for threshold derivation.
	 *
	 * @param standardError Standard error of the observed rate
	 * @param confidenceIntervalLower Lower bound of 95% confidence interval
	 * @param confidenceIntervalUpper Upper bound of 95% confidence interval
	 * @param failureDistribution Count of failures by category
	 * @param totalTimeMs Total experiment execution time
	 * @param avgTimePerSampleMs Average time per sample
	 * @param totalTokens Total tokens consumed
	 * @param avgTokensPerSample Average tokens per sample
	 */
	public record ExtendedStatistics(
			double standardError,
			double confidenceIntervalLower,
			double confidenceIntervalUpper,
			Map<String, Integer> failureDistribution,
			long totalTimeMs,
			long avgTimePerSampleMs,
			long totalTokens,
			long avgTokensPerSample
	) {
		public ExtendedStatistics {
			failureDistribution = failureDistribution != null
					? Collections.unmodifiableMap(new LinkedHashMap<>(failureDistribution))
					: Collections.emptyMap();
		}
	}

	/**
	 * Metadata about the factor source used in the experiment.
	 *
	 * <p>This enables factor consistency verification between experiments and
	 * probabilistic tests. If the test uses the same factor source (same hash),
	 * the factors consumed are guaranteed to be identical for the overlapping
	 * portion (first-N prefix selection).
	 *
	 * @param sourceHash Hash identifying the factor source (source-owned, not consumption-based)
	 * @param sourceName Name of the factor source (method name or explicit identifier)
	 * @param samplesUsed Number of factors consumed during the experiment
	 * @param earlyTermination True if the experiment terminated early
	 */
	public record FactorSourceMetadata(
			String sourceHash,
			String sourceName,
			int samplesUsed,
			boolean earlyTermination
	) {
		/**
		 * Returns true if this metadata has a valid hash for comparison.
		 */
		public boolean hasHash() {
			return sourceHash != null && !sourceHash.isEmpty();
		}
	}

	public static final class Builder {

		private String serviceContractId;
		private int version = 1;
		private Instant generatedAt;
		private Instant approvedAt;
		private String approvedBy;
		private String approvalNotes;
		private List<String> sourceBaselines;
		private Map<String, Object> executionContext;
		private SpecRequirements requirements;
		private CostEnvelope costEnvelope;
		private EmpiricalBasis empiricalBasis;
		private ExtendedStatistics extendedStatistics;
		private FactorSourceMetadata factorSourceMetadata;
		private ExpirationPolicy expirationPolicy;
		private CovariateProfile covariateProfile;
		private String footprint;
		private LatencyBaseline latencyBaseline;
		private ServiceContractAttributes serviceContractAttributes;

		private Builder() {
		}

		public Builder serviceContractId(String serviceContractId) {
			this.serviceContractId = serviceContractId;
			return this;
		}

		public Builder version(int version) {
			this.version = version;
			return this;
		}

		public Builder generatedAt(Instant generatedAt) {
			this.generatedAt = generatedAt;
			return this;
		}

		public Builder approvedAt(Instant approvedAt) {
			this.approvedAt = approvedAt;
			return this;
		}

		public Builder approvedBy(String approvedBy) {
			this.approvedBy = approvedBy;
			return this;
		}

		public Builder approvalNotes(String approvalNotes) {
			this.approvalNotes = approvalNotes;
			return this;
		}

		public Builder sourceBaselines(List<String> sourceBaselines) {
			this.sourceBaselines = sourceBaselines;
			return this;
		}

		public Builder executionContext(Map<String, Object> executionContext) {
			this.executionContext = executionContext;
			return this;
		}

		public Builder requirements(SpecRequirements requirements) {
			this.requirements = requirements;
			return this;
		}

		public Builder requirements(double minPassRate, String successCriteria) {
			this.requirements = new SpecRequirements(minPassRate, successCriteria);
			return this;
		}

		public Builder costEnvelope(CostEnvelope costEnvelope) {
			this.costEnvelope = costEnvelope;
			return this;
		}

		public Builder costEnvelope(long maxTimePerSampleMs, long maxTokensPerSample, long totalTokenBudget) {
			this.costEnvelope = new CostEnvelope(maxTimePerSampleMs, maxTokensPerSample, totalTokenBudget);
			return this;
		}

		public Builder empiricalBasis(EmpiricalBasis empiricalBasis) {
			this.empiricalBasis = empiricalBasis;
			return this;
		}

		public Builder empiricalBasis(int samples, int successes, Instant generatedAt) {
			this.empiricalBasis = new EmpiricalBasis(samples, successes, generatedAt);
			return this;
		}

		public Builder empiricalBasis(int samples, int successes) {
			this.empiricalBasis = new EmpiricalBasis(samples, successes, null);
			return this;
		}

		public Builder extendedStatistics(ExtendedStatistics extendedStatistics) {
			this.extendedStatistics = extendedStatistics;
			return this;
		}

		public Builder factorSourceMetadata(FactorSourceMetadata factorSourceMetadata) {
			this.factorSourceMetadata = factorSourceMetadata;
			return this;
		}

		public Builder factorSourceMetadata(String sourceHash, String sourceName, int samplesUsed) {
			this.factorSourceMetadata = new FactorSourceMetadata(sourceHash, sourceName, samplesUsed, false);
			return this;
		}

		public Builder factorSourceMetadata(String sourceHash, String sourceName, int samplesUsed, boolean earlyTermination) {
			this.factorSourceMetadata = new FactorSourceMetadata(sourceHash, sourceName, samplesUsed, earlyTermination);
			return this;
		}

		/**
		 * Sets the expiration policy for this specification.
		 *
		 * @param expirationPolicy the expiration policy
		 * @return this builder
		 */
		public Builder expirationPolicy(ExpirationPolicy expirationPolicy) {
			this.expirationPolicy = expirationPolicy;
			return this;
		}

		/**
		 * Sets the expiration policy for this specification.
		 *
		 * @param expiresInDays the validity period in days (0 = no expiration)
		 * @param baselineEndTime the experiment end time
		 * @return this builder
		 */
		public Builder expirationPolicy(int expiresInDays, Instant baselineEndTime) {
			if (expiresInDays > 0) {
				this.expirationPolicy = ExpirationPolicy.of(expiresInDays, baselineEndTime);
			} else {
				this.expirationPolicy = null;
			}
			return this;
		}

		/**
		 * Sets the covariate profile for this specification.
		 *
		 * @param covariateProfile the covariate profile
		 * @return this builder
		 */
		public Builder covariateProfile(CovariateProfile covariateProfile) {
			this.covariateProfile = covariateProfile;
			return this;
		}

		/**
		 * Sets the invocation footprint for this specification.
		 *
		 * @param footprint the footprint hash
		 * @return this builder
		 */
		public Builder footprint(String footprint) {
			this.footprint = footprint;
			return this;
		}

		/**
		 * Sets the latency baseline for this specification.
		 *
		 * @param latencyBaseline the latency baseline (may be null)
		 * @return this builder
		 */
		public Builder latencyBaseline(LatencyBaseline latencyBaseline) {
			this.latencyBaseline = latencyBaseline;
			return this;
		}

		public Builder serviceContractAttributes(ServiceContractAttributes serviceContractAttributes) {
			this.serviceContractAttributes = serviceContractAttributes;
			return this;
		}

		public Builder warmup(int warmup) {
			if (this.serviceContractAttributes == null) {
				this.serviceContractAttributes = new ServiceContractAttributes(warmup);
			} else {
				this.serviceContractAttributes = new ServiceContractAttributes(warmup, this.serviceContractAttributes.maxConcurrent());
			}
			return this;
		}

		public ExecutionSpecification build() {
			return new ExecutionSpecification(this);
		}
	}
}
