package org.mavai.punit.report;

import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.function.Function;

import org.mavai.punit.internal.engine.emit.LatencySection;

/**
 * Shared section renderers for the Explore and Optimize comparison reports
 * ({@code org.mavai.punit.report.explore} and {@code org.mavai.punit.report.optimize}).
 *
 * <p>The two reports compare a different kind of row — a variant (a factor
 * combination) versus an iteration (a mutate/score step) — but render
 * several sections identically once that row is reduced to the primitives
 * each section actually needs: a header/footer document shell, a
 * per-criterion matrix, and the latency/cost/termination/pass-rate table
 * cells. Each such section lives here once; the per-package {@code
 * HtmlWriter} supplies only what's genuinely report-specific (the overview,
 * the leaderboard/iteration table, the near-tie legend wording, latency
 * strips vs. score trajectory).
 */
public final class ComparisonReportHtml {

    private static final DateTimeFormatter TIMESTAMP_FORMAT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss z")
                    .withZone(ZoneId.systemDefault());

    /** Percentile / token "not available" sentinel, rendered as a dash. */
    public static final long UNAVAILABLE = LatencySection.PERCENTILE_UNAVAILABLE_MS;

    private ComparisonReportHtml() {
    }

    // ── Document shell ───────────────────────────────────────────────────────

    public static String formattedTimestamp(Instant now) {
        return TIMESTAMP_FORMAT.format(now);
    }

    public static void appendDocumentHead(StringBuilder html, String title) {
        html.append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
        html.append("<meta charset=\"UTF-8\">\n");
        html.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        html.append("<title>").append(ReportHtml.escape(title)).append("</title>\n");
    }

    public static void appendHeader(StringBuilder html, String title, Instant now) {
        html.append("<header>\n");
        html.append("<h1>").append(ReportHtml.escape(title)).append("</h1>\n");
        html.append("<p class=\"timestamp\">Generated: ")
                .append(ReportHtml.escape(formattedTimestamp(now))).append("</p>\n");
        html.append("</header>\n");
    }

    public static void appendFooter(StringBuilder html, Instant now) {
        html.append("<footer>\n");
        html.append("<p>Generated by PUnit at ")
                .append(ReportHtml.escape(formattedTimestamp(now))).append("</p>\n");
        html.append("</footer>\n");
    }

    // ── Per-criterion matrix ────────────────────────────────────────────────

    /**
     * Renders the "Per-criterion comparison" matrix: one row per {@code row},
     * one column per criterion (the union across all rows, in encounter
     * order). Renders nothing when the union of criteria is empty.
     *
     * @param rowHeader  the header cell for the row-label column ("Variant",
     *                   "Iteration")
     * @param rows       the rows in the order they should be rendered
     * @param rowLabel   each row's display label
     * @param criteriaOf each row's per-criterion results, keyed by criterion id
     */
    public static <T> void appendCriterionMatrix(StringBuilder html, String rowHeader,
            List<T> rows, Function<T, String> rowLabel, Function<T, Map<String, CriterionResult>> criteriaOf) {
        Set<String> criteria = new LinkedHashSet<>();
        rows.forEach(row -> criteria.addAll(criteriaOf.apply(row).keySet()));
        if (criteria.isEmpty()) {
            return;
        }
        html.append("<h3>Per-criterion comparison</h3>\n");
        html.append("<table class=\"criterion-matrix\">\n<thead>\n<tr><th>")
                .append(ReportHtml.escape(rowHeader)).append("</th>");
        for (String criterion : criteria) {
            html.append("<th>").append(ReportHtml.escape(criterion)).append("</th>");
        }
        html.append("</tr>\n</thead>\n<tbody>\n");
        for (T row : rows) {
            html.append("<tr>\n<td class=\"criterion-name\">")
                    .append(ReportHtml.escape(rowLabel.apply(row))).append("</td>\n");
            Map<String, CriterionResult> rowCriteria = criteriaOf.apply(row);
            for (String criterion : criteria) {
                appendCriterionCell(html, rowCriteria.get(criterion));
            }
            html.append("</tr>\n");
        }
        html.append("</tbody>\n</table>\n");
    }

    private static void appendCriterionCell(StringBuilder html, CriterionResult result) {
        if (result == null) {
            html.append("<td class=\"cell-na\"><span class=\"muted\">n/a</span></td>\n");
            return;
        }
        String rateClass = result.observedPassRate() >= 1.0 ? "punit-pass"
                : result.observedPassRate() <= 0.0 ? "punit-fail" : "";
        html.append("<td class=\"cell\">");
        html.append("<div class=\"bar-track narrow\"><div class=\"bar-fill pass\" style=\"width:")
                .append(percent(result.observedPassRate())).append("\"></div></div>");
        html.append("<span class=\"").append(rateClass).append("\">")
                .append(formatRate(result.observedPassRate())).append("</span>");
        html.append("</td>\n");
    }

    // ── Shared table cells ───────────────────────────────────────────────────

    public static void appendPassRateCell(StringBuilder html, boolean hasNoSamples,
            int successes, int sampleCount, double observedRate, String rateSpanClass) {
        html.append("<td class=\"passrate\">\n");
        if (hasNoSamples) {
            html.append("<div class=\"bar-track\"></div>\n");
            html.append("<span class=\"punit-inconclusive\">0/0</span>\n");
        } else {
            html.append("<div class=\"bar-track\">");
            html.append("<div class=\"bar-fill fail\" style=\"width:100%\"></div>");
            html.append("<div class=\"bar-fill pass\" style=\"width:")
                    .append(percent(observedRate)).append("\"></div>");
            html.append("</div>\n");
            html.append("<span class=\"").append(rateSpanClass).append("\">")
                    .append(successes).append("/").append(sampleCount)
                    .append(" (").append(formatRate(observedRate)).append(")</span>\n");
        }
        html.append("</td>\n");
    }

    public static void appendLatencyCell(StringBuilder html, long valueMs, long maxLatency) {
        html.append("<td class=\"latency\">");
        if (valueMs == UNAVAILABLE) {
            html.append("<span class=\"muted\">-</span>");
        } else {
            html.append("<div class=\"bar-track narrow\"><div class=\"bar-fill muted\" style=\"width:")
                    .append(percent((double) valueMs / maxLatency)).append("\"></div></div>");
            html.append("<span>").append(valueMs).append("ms</span>");
        }
        html.append("</td>\n");
    }

    public static void appendCostCell(StringBuilder html, long avgTimePerSampleMs, long totalTokens, long maxAvg) {
        html.append("<td class=\"cost\">");
        html.append("<div class=\"bar-track narrow\"><div class=\"bar-fill muted\" style=\"width:")
                .append(percent((double) avgTimePerSampleMs / maxAvg)).append("\"></div></div>");
        html.append("<span>").append(avgTimePerSampleMs).append("ms");
        if (totalTokens != UNAVAILABLE) {
            html.append(" &middot; ").append(totalTokens).append(" tok");
        }
        html.append("</span></td>\n");
    }

    public static void appendTerminationCell(StringBuilder html, String reason) {
        String text = reason == null ? "&mdash;" : ReportHtml.escape(reason);
        boolean completed = "COMPLETED".equals(reason);
        html.append("<td><span class=\"badge ").append(completed ? "ok" : "warn").append("\">")
                .append(text).append("</span></td>\n");
    }

    // ── Number formatting ────────────────────────────────────────────────────

    public static String percent(double fraction) {
        double clamped = Math.max(0.0, Math.min(1.0, fraction));
        return String.format(Locale.ROOT, "%.2f%%", clamped * 100.0);
    }

    public static String formatRate(double rate) {
        return String.format(Locale.ROOT, "%.1f%%", rate * 100.0);
    }

    public static String round(double value) {
        return String.format(Locale.ROOT, "%.1f", value);
    }

    // ── Shared chart CSS ─────────────────────────────────────────────────────

    /**
     * The chart-style rules common to both comparison reports: section/heading
     * spacing, the tie-mark/tie-legend idiom, the CSS-width bar-track/bar-fill
     * primitive, badges, the factor-list {@code <dl>}, and the criterion-matrix
     * cell styling. Each report's own {@code HtmlWriter} appends this first,
     * then its own report-specific rules (e.g. best-row highlighting, the
     * score-trajectory SVG).
     */
    public static void appendSharedChartCss(StringBuilder html) {
        html.append("""
                h3 { font-size: 1rem; margin: 1rem 0 0.5rem; color: var(--text-color); }
                .service { margin-bottom: 2.5rem; }
                .overview { margin-bottom: 2rem; }
                p.empty { color: var(--text-muted); font-style: italic; }
                td.rank, td.num { text-align: right; font-variant-numeric: tabular-nums; }
                .tie-mark {
                    color: var(--text-muted);
                    font-weight: 600;
                    margin-left: 0.15rem;
                    cursor: help;
                }
                p.tie-legend {
                    margin: -1rem 0 1.5rem;
                    padding: 0.5rem 0.75rem;
                    background: var(--bg-light);
                    border: 1px solid var(--border-color);
                    border-left: 3px solid var(--text-muted);
                    border-radius: 4px;
                    font-size: 0.8125rem;
                    color: var(--text-color);
                    line-height: 1.5;
                }
                table.leaderboard td { vertical-align: middle; }
                .bar-track {
                    position: relative;
                    display: inline-block;
                    width: 120px;
                    height: 0.9rem;
                    background: var(--bg-light);
                    border: 1px solid var(--border-color);
                    border-radius: 3px;
                    overflow: hidden;
                    vertical-align: middle;
                }
                .bar-track.narrow { width: 80px; }
                .bar-fill {
                    position: absolute;
                    left: 0;
                    top: 0;
                    bottom: 0;
                }
                .bar-fill.pass { background: var(--pass-color); }
                .bar-fill.fail { background: var(--fail-color); }
                .bar-fill.muted { background: #adb5bd; }
                td.score span, td.passrate span, td.latency span, td.cost span, td.cell span {
                    margin-left: 0.4rem;
                    font-variant-numeric: tabular-nums;
                    font-size: 0.8125rem;
                }
                .muted { color: var(--text-muted); }
                .badge {
                    display: inline-block;
                    padding: 0.1rem 0.5rem;
                    border-radius: 3px;
                    font-size: 0.75rem;
                    font-weight: 600;
                }
                .badge.ok { background: #e8f5e9; color: var(--pass-color); }
                .badge.warn { background: #fff8e1; color: #b26a00; border: 1px solid #f9a825; }
                dl.factor-list {
                    display: grid;
                    grid-template-columns: max-content 1fr;
                    column-gap: 1rem;
                    row-gap: 0.25rem;
                    margin: 0.5rem 0 0.25rem 0.5rem;
                    font-size: 0.8125rem;
                }
                dl.factor-list dt { color: var(--text-muted); font-family: monospace; }
                dl.factor-list dd { margin: 0; }
                dl.factor-list pre {
                    margin: 0;
                    white-space: pre-wrap;
                    word-wrap: break-word;
                    font-size: 0.8125rem;
                }
                table.criterion-matrix td.criterion-name { font-family: monospace; font-size: 0.8125rem; }
                table.criterion-matrix td.cell, table.criterion-matrix td.cell-na { white-space: nowrap; }
                """);
    }
}
