package org.mavai.punit.sentinel;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.lang.reflect.Method;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import java.util.Optional;

import org.mavai.punit.api.Experiment;
import org.mavai.punit.api.ProbabilisticTest;
import org.mavai.punit.internal.reporting.ConsoleVerdictSink;
import org.mavai.punit.verdict.ProbabilisticTestVerdict;

/**
 * CLI entrypoint for Sentinel execution.
 *
 * <p>Reads the list of registered classes from a build-time manifest
 * ({@value #MANIFEST_RESOURCE}) generated by the punit Gradle plugin's
 * {@code createSentinel} task, then dispatches typed
 * {@code @ProbabilisticTest} or {@code @Experiment} methods through
 * {@link SentinelOrchestrator}.
 *
 * <h2>Usage</h2>
 * <pre>
 * java -jar sentinel.jar --help
 * java -jar sentinel.jar --list
 * java -jar sentinel.jar test [--verbose]
 * java -jar sentinel.jar exp  [--verbose]
 * </pre>
 *
 * <h2>Exit codes</h2>
 * <ul>
 *   <li>0 — all tests / experiments passed (or {@code --help} / {@code --list})</li>
 *   <li>1 — one or more tests / experiments failed, or no methods executed</li>
 *   <li>2 — usage error (bad arguments, missing manifest)</li>
 * </ul>
 */
public class SentinelMain {

    static final String MANIFEST_RESOURCE = "META-INF/punit/sentinel-classes";
    static final int EXIT_SUCCESS = 0;
    static final int EXIT_FAILURE = 1;
    static final int EXIT_USAGE = 2;

    private final String[] args;
    private final SystemBridge system;

    /**
     * Abstraction over system-level operations to enable testing
     * without {@code System.exit()} or real classloader lookups.
     */
    interface SystemBridge {
        void exit(int code);
        ClassLoader getClassLoader();
    }

    SentinelMain(String[] args, SystemBridge system) {
        this.args = args;
        this.system = system;
    }

    // javai-ref: JVI-PYF4FP9 — do not remove (resolves in javai-orchestrator)
    // javai-ref: JVI-P37E1Y2 — do not remove (resolves in javai-orchestrator)
    // javai-ref: JVI-D0BEKXM — do not remove (resolves in javai-orchestrator)
    public static void main(String[] args) {
        new SentinelMain(args, new RealSystemBridge()).run();
    }

    void run() {
        ParsedArgs parsed = parseArgs();

        if (parsed.help) {
            printHelp(System.out);
            system.exit(EXIT_SUCCESS);
            return;
        }

        if (parsed.list) {
            runList();
            return;
        }

        if (parsed.command == null) {
            printHelp(System.err);
            system.exit(EXIT_USAGE);
            return;
        }

        if (!parsed.command.equals("test")
                && !parsed.command.equals("exp")
                && !parsed.command.equals("experiment")) {
            System.err.println("Unknown command: " + parsed.command);
            printHelp(System.err);
            system.exit(EXIT_USAGE);
            return;
        }

        boolean isTest = parsed.command.equals("test");

        List<Class<?>> sentinelClasses = discoverSentinelClasses();
        if (sentinelClasses == null) {
            return; // error reported, exit invoked
        }

        SentinelConfiguration.Builder configBuilder = SentinelConfiguration.builder()
                .sentinelClasses(sentinelClasses);
        if (parsed.verbose && isTest) {
            configBuilder.verdictSink(new ConsoleVerdictSink());
        }
        SentinelConfiguration config = configBuilder.build();

        SentinelOrchestrator orchestrator = new SentinelOrchestrator();
        Instant start = Instant.now();
        List<SentinelExecutor.Outcome> outcomes = isTest
                ? orchestrator.runTests(sentinelClasses)
                : orchestrator.runExperiments(sentinelClasses);
        Duration duration = Duration.between(start, Instant.now());

        // Forward each captured verdict to the configured sink — the
        // verdict bus's capture mechanism inside the executor is internal;
        // user-configured sinks receive verdicts here.
        for (SentinelExecutor.Outcome outcome : outcomes) {
            outcome.verdict().ifPresent(config.verdictSink()::accept);
        }

        SentinelResult result = aggregate(outcomes, duration);

        SentinelConsoleReporter reporter = new SentinelConsoleReporter(System.out);
        if (isTest) {
            reporter.printTestSummary(result);
        } else {
            reporter.printExperimentSummary(result);
        }

        if (result.noneExecuted()) {
            system.exit(EXIT_FAILURE);
        } else {
            system.exit(result.allPassed() ? EXIT_SUCCESS : EXIT_FAILURE);
        }
    }

    private void runList() {
        List<Class<?>> sentinelClasses = discoverSentinelClasses();
        if (sentinelClasses == null) {
            return;
        }
        StringBuilder sb = new StringBuilder();
        sb.append("Registered classes and methods:\n\n");
        for (Class<?> cls : sentinelClasses) {
            sb.append("  ").append(cls.getName()).append('\n');
            for (Method m : cls.getDeclaredMethods()) {
                if (m.isAnnotationPresent(ProbabilisticTest.class)) {
                    sb.append("    [test] ").append(m.getName()).append('\n');
                } else if (m.isAnnotationPresent(Experiment.class)) {
                    sb.append("    [exp]  ").append(m.getName()).append('\n');
                }
            }
        }
        System.out.print(sb);
        system.exit(EXIT_SUCCESS);
    }

    /**
     * Aggregates per-method outcomes into the suite-level
     * {@link SentinelResult} the reporter and exit-code logic consume.
     *
     * <p>An outcome with a verdict counts toward passed or failed based
     * on {@link ProbabilisticTestVerdict#junitPassed()}. An outcome
     * without a verdict (defect-before-emit) counts as skipped.
     */
    private SentinelResult aggregate(
            List<SentinelExecutor.Outcome> outcomes, Duration duration) {
        List<ProbabilisticTestVerdict> verdicts = outcomes.stream()
                .map(SentinelExecutor.Outcome::verdict)
                .filter(Optional::isPresent)
                .map(Optional::get)
                .toList();
        int passed = (int) outcomes.stream()
                .filter(o -> o.verdict().map(ProbabilisticTestVerdict::junitPassed).orElse(false))
                .count();
        int failed = (int) outcomes.stream()
                .filter(o -> o.verdict().map(v -> !v.junitPassed()).orElse(false))
                .count();
        int skipped = (int) outcomes.stream()
                .filter(o -> o.verdict().isEmpty())
                .count();
        return new SentinelResult(
                passed + failed + skipped, passed, failed, skipped,
                verdicts, duration);
    }

    /**
     * Loads the registered classes from the build-time manifest.
     * Returns {@code null} on failure (after reporting the error and
     * invoking {@code system.exit}).
     */
    private List<Class<?>> discoverSentinelClasses() {
        List<Class<?>> sentinelClasses;
        try {
            sentinelClasses = loadSentinelClasses();
        } catch (SentinelExecutionException e) {
            System.err.println(e.getMessage());
            system.exit(EXIT_USAGE);
            return null;
        }
        if (sentinelClasses.isEmpty()) {
            System.err.println(
                    "No registered classes found. Ensure the JAR was built with the "
                            + "createSentinel Gradle task, which generates the "
                            + MANIFEST_RESOURCE + " manifest.");
            system.exit(EXIT_USAGE);
            return null;
        }
        return sentinelClasses;
    }

    // ── Argument parsing ─────────────────────────────────────────────────

    static class ParsedArgs {
        String command;
        boolean verbose;
        boolean help;
        boolean list;
    }

    ParsedArgs parseArgs() {
        ParsedArgs parsed = new ParsedArgs();
        List<String> positional = new ArrayList<>();

        for (String arg : args) {
            switch (arg) {
                case "--help", "-h" -> parsed.help = true;
                case "--list" -> parsed.list = true;
                case "--verbose" -> parsed.verbose = true;
                default -> positional.add(arg);
            }
        }

        if (!positional.isEmpty()) {
            parsed.command = positional.getFirst();
        }
        return parsed;
    }

    // ── Help ─────────────────────────────────────────────────────────────

    private void printHelp(java.io.PrintStream stream) {
        stream.println("PUnit Sentinel — typed-pipeline probabilistic test and experiment runner");
        stream.println();
        stream.println("Usage: java -jar sentinel.jar <command> [options]");
        stream.println();
        stream.println("Commands:");
        stream.println("  test         Run @ProbabilisticTest methods on registered classes");
        stream.println("  exp          Run @Experiment methods on registered classes");
        stream.println();
        stream.println("Options:");
        stream.println("  --help       Show this help message and exit");
        stream.println("  --list       List registered classes and their methods, then exit");
        stream.println("  --verbose    Show every verdict on the console");
        stream.println();
        stream.println("Exit codes:");
        stream.println("  0  All tests / experiments passed (or --help / --list)");
        stream.println("  1  One or more failed, or no methods executed");
        stream.println("  2  Usage error");
    }

    // ── Manifest loading ─────────────────────────────────────────────────

    List<Class<?>> loadSentinelClasses() {
        List<String> classNames = loadManifestEntries();
        List<Class<?>> classes = new ArrayList<>();
        ClassLoader classLoader = system.getClassLoader();
        for (String className : classNames) {
            try {
                classes.add(Class.forName(className, true, classLoader));
            } catch (ClassNotFoundException e) {
                throw new SentinelExecutionException(
                        "Registered class not found on classpath: " + className, e);
            }
        }
        return classes;
    }

    private List<String> loadManifestEntries() {
        List<String> entries = new ArrayList<>();
        ClassLoader classLoader = system.getClassLoader();
        try {
            Enumeration<URL> resources = classLoader.getResources(MANIFEST_RESOURCE);
            while (resources.hasMoreElements()) {
                URL resource = resources.nextElement();
                try (BufferedReader reader = new BufferedReader(
                        new InputStreamReader(resource.openStream(), StandardCharsets.UTF_8))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        String trimmed = line.trim();
                        if (!trimmed.isEmpty() && !trimmed.startsWith("#")) {
                            entries.add(trimmed);
                        }
                    }
                }
            }
        } catch (IOException e) {
            throw new SentinelExecutionException(
                    "Failed to read sentinel class manifest: " + MANIFEST_RESOURCE, e);
        }
        return entries;
    }

    private static class RealSystemBridge implements SystemBridge {
        @Override
        public void exit(int code) {
            System.exit(code);
        }

        @Override
        public ClassLoader getClassLoader() {
            return Thread.currentThread().getContextClassLoader();
        }
    }
}
